# Setup
title:            "Drago's Blog"
url:              'https://drago1234.github.io/'
giturl:           'https://drago1234.github.io/'
baseurl:          'https://drago1234.github.io/'
home_url:          '/about_me/index.html'
paginate:         7
rss:              'atom.xml'

# Build settings (Reference for more theme: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#theme)
# theme: minima 
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# About
author:           
  name:           'Drago'
email: dong.760@outlook.com
github_username:  Drago1234
disqus_shortname: zhengqi
favicon:     "/public/triple_spiral.jpg"

# List of pages to include in the masthead of the website
pages_list:
  About:          '/about_me/index.html'
  Resume:         '/Zhengqi_Dong_Underg_OSU_CSE_2021.pdf'
  Knowledge Bank: '/Knowledge_bank/Knowledge_bank_home.html'
  Categories:     '/categories'
  Tags:           '/tags'
  Archive:        '/archive'
  Feed:           '/atom.xml'

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

# YAML front matter defaults
defaults:
  - scope:
      path:       ''
      type:       posts
    values:
      layout:     post
      related:    true
      comments:   true
  - scope:
      path:       ""
      type:       default
    values:
      layout:     default
      related:    true
      comments:   true

# Comments
disqus:           'zhengqi'

# Dependencies
markdown:         kramdown
highlighter:      rouge
lsi:              false
incremental:      false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Outputting
permalink:        pretty
paginate:         7                      # amount of posts to show per page
paginate_path:    '/page:num'
timezone:         'America/New_York'  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-MDGF2668GJ"
